//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressEN.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addressEN.
        /// </summary>
        internal static string addressF {
            get {
                return ResourceManager.GetString("addressF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add card.
        /// </summary>
        internal static string addtocart {
            get {
                return ResourceManager.GetString("addtocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string align {
            get {
                return ResourceManager.GetString("align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string align1 {
            get {
                return ResourceManager.GetString("align1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقالات.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلس ها.
        /// </summary>
        internal static string Atlas {
            get {
                return ResourceManager.GetString("Atlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وبلاگ ها.
        /// </summary>
        internal static string Blogs {
            get {
                return ResourceManager.GetString("Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your web log has been registered successfully.
        /// </summary>
        internal static string Blog_Succcess_Inser {
            get {
                return ResourceManager.GetString("Blog_Succcess_Inser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code :.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let others send their idea..
        /// </summary>
        internal static string Comment_Tick {
            get {
                return ResourceManager.GetString("Comment_Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت ها.
        /// </summary>
        internal static string Companys {
            get {
                return ResourceManager.GetString("Companys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس باما.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس باما.
        /// </summary>
        internal static string ContactUs1 {
            get {
                return ResourceManager.GetString("ContactUs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string Delete_Confirm {
            get {
                return ResourceManager.GetString("Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailsEN.
        /// </summary>
        internal static string DetailsF {
            get {
                return ResourceManager.GetString("DetailsF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string DetailsImage {
            get {
                return ResourceManager.GetString("DetailsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string dir1 {
            get {
                return ResourceManager.GetString("dir1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Edit_Bottom {
            get {
                return ResourceManager.GetString("Edit_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an error reported while operating.
        /// </summary>
        internal static string Error_ShowMss {
            get {
                return ResourceManager.GetString("Error_ShowMss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسش و پاسخ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FoodsEN.
        /// </summary>
        internal static string Foods {
            get {
                return ResourceManager.GetString("Foods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.&lt;a href=&quot;http://Phasco.ir &quot;&gt; Pharmed Avarad Sabz Company.&lt;/a&gt;.
        /// </summary>
        internal static string Footer1 {
            get {
                return ResourceManager.GetString("Footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        internal static string Home_Page {
            get {
                return ResourceManager.GetString("Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemEN.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آزمایشگاه ها.
        /// </summary>
        internal static string Labs {
            get {
                return ResourceManager.GetString("Labs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        internal static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  First, please log in.
        /// </summary>
        internal static string Login_First {
            get {
                return ResourceManager.GetString("Login_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری يا رمز معتبر نمی باشد.
        /// </summary>
        internal static string Login_Msg_Invalid {
            get {
                return ResourceManager.GetString("Login_Msg_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagerEN.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        internal static string MonyUnit {
            get {
                return ResourceManager.GetString("MonyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mss.
        /// </summary>
        internal static string Mss {
            get {
                return ResourceManager.GetString("Mss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameEn.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nameEN.
        /// </summary>
        internal static string nameF {
            get {
                return ResourceManager.GetString("nameF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Laboratory.
        /// </summary>
        internal static string Nlab {
            get {
                return ResourceManager.GetString("Nlab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font color=&apos;#fb0206&apos;&gt;For Your Searched Items, There are no results&lt;/font&gt;.
        /// </summary>
        internal static string nofound {
            get {
                return ResourceManager.GetString("nofound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OutBox {
            get {
                return ResourceManager.GetString("OutBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Page_Register {
            get {
                return ResourceManager.GetString("Page_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phasco news.
        /// </summary>
        internal static string Phasco_News {
            get {
                return ResourceManager.GetString("Phasco_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید ترین مقالات.
        /// </summary>
        internal static string Phasco_New_Article {
            get {
                return ResourceManager.GetString("Phasco_New_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرخواننده ترین مقالات.
        /// </summary>
        internal static string PHasco_Top_Articel {
            get {
                return ResourceManager.GetString("PHasco_Top_Articel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران فاسکو.
        /// </summary>
        internal static string Phasco_Users {
            get {
                return ResourceManager.GetString("Phasco_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest Users.
        /// </summary>
        internal static string Phasco_Users_Newst {
            get {
                return ResourceManager.GetString("Phasco_Users_Newst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phsco Blog&apos;s.
        /// </summary>
        internal static string Phasco_WEblog {
            get {
                return ResourceManager.GetString("Phasco_WEblog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price :.
        /// </summary>
        internal static string Price_Text {
            get {
                return ResourceManager.GetString("Price_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment : .
        /// </summary>
        internal static string Product_Comment {
            get {
                return ResourceManager.GetString("Product_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX :.
        /// </summary>
        internal static string Product_Group {
            get {
                return ResourceManager.GetString("Product_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name : .
        /// </summary>
        internal static string Product_name {
            get {
                return ResourceManager.GetString("Product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string province1 {
            get {
                return ResourceManager.GetString("province1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qty :.
        /// </summary>
        internal static string qty {
            get {
                return ResourceManager.GetString("qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionEN.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Reg_Form_Submit {
            get {
                return ResourceManager.GetString("Reg_Form_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itmes Found.
        /// </summary>
        internal static string Res1 {
            get {
                return ResourceManager.GetString("Res1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Res2 {
            get {
                return ResourceManager.GetString("Res2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        internal static string R_Address {
            get {
                return ResourceManager.GetString("R_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdat.
        /// </summary>
        internal static string R_Birthday {
            get {
                return ResourceManager.GetString("R_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Day Location.
        /// </summary>
        internal static string R_BirthDayLocation {
            get {
                return ResourceManager.GetString("R_BirthDayLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        internal static string R_Birthday_Day {
            get {
                return ResourceManager.GetString("R_Birthday_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        internal static string R_Birthday_Month {
            get {
                return ResourceManager.GetString("R_Birthday_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        internal static string R_Birthday_Year {
            get {
                return ResourceManager.GetString("R_Birthday_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string R_City {
            get {
                return ResourceManager.GetString("R_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string R_country {
            get {
                return ResourceManager.GetString("R_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیک.
        /// </summary>
        internal static string R_Email {
            get {
                return ResourceManager.GetString("R_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام های رمز وارده با هم يکسان نمي باشد . هردو نام رمز وارده بايد با هم يکسان باشند .مجددا وارد نمائيد.  .
        /// </summary>
        internal static string R_err_confirm_Password {
            get {
                return ResourceManager.GetString("R_err_confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیک نا معتبر است.
        /// </summary>
        internal static string R_err_Email {
            get {
                return ResourceManager.GetString("R_err_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر محترم ضمن تقدیر و تشکر، مشخصات شما با موفقيت درج گرديد..
        /// </summary>
        internal static string R_err_Final {
            get {
                return ResourceManager.GetString("R_err_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پس از بررسی مدير سایت و در صورت تایید، تائیدیه نام کاربری و رمز عبور شما به آدرس پست الکترونیکی شما ارسال می گردد.( توجه : اگر از خدمات پست الکترونيک Yahoo استفاده می کنید ممکن است نامه مربوطه به قسمت Bulk ارسال شود).
        ///.
        /// </summary>
        internal static string R_err_Final_Massge {
            get {
                return ResourceManager.GetString("R_err_Final_Massge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نام کاربری وارده قبلا ثبت شده نام کاربری ديگری را وارد کنيد. .
        /// </summary>
        internal static string R_err_Has_Uid {
            get {
                return ResourceManager.GetString("R_err_Has_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمينه فعاليت مؤسسه.
        /// </summary>
        internal static string R_Example {
            get {
                return ResourceManager.GetString("R_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX.
        /// </summary>
        internal static string R_fax {
            get {
                return ResourceManager.GetString("R_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زن.
        /// </summary>
        internal static string R_Female {
            get {
                return ResourceManager.GetString("R_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string R_Firstname {
            get {
                return ResourceManager.GetString("R_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducer.
        /// </summary>
        internal static string R_Intro {
            get {
                return ResourceManager.GetString("R_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مؤسسه / نام آزمايشگاه.
        /// </summary>
        internal static string R_Lab_Name {
            get {
                return ResourceManager.GetString("R_Lab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string R_Lastname {
            get {
                return ResourceManager.GetString("R_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرد.
        /// </summary>
        internal static string R_Male {
            get {
                return ResourceManager.GetString("R_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مدير / مسئول فنی.
        /// </summary>
        internal static string R_Manager {
            get {
                return ResourceManager.GetString("R_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاهل .
        /// </summary>
        internal static string R_Marride {
            get {
                return ResourceManager.GetString("R_Marride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاهل.
        /// </summary>
        internal static string R_Marride_M {
            get {
                return ResourceManager.GetString("R_Marride_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجرد.
        /// </summary>
        internal static string R_Marride_S {
            get {
                return ResourceManager.GetString("R_Marride_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        internal static string R_Mobile {
            get {
                return ResourceManager.GetString("R_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string R_Pass {
            get {
                return ResourceManager.GetString("R_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string R_rpass {
            get {
                return ResourceManager.GetString("R_rpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی.
        /// </summary>
        internal static string R_r_Study {
            get {
                return ResourceManager.GetString("R_r_Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        internal static string R_SEX {
            get {
                return ResourceManager.GetString("R_SEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string R_State {
            get {
                return ResourceManager.GetString("R_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحصیلات.
        /// </summary>
        internal static string R_Study {
            get {
                return ResourceManager.GetString("R_Study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فوق دکترا.
        /// </summary>
        internal static string R_Study01 {
            get {
                return ResourceManager.GetString("R_Study01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکترا.
        /// </summary>
        internal static string R_Study02 {
            get {
                return ResourceManager.GetString("R_Study02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی ارشد.
        /// </summary>
        internal static string R_Study03 {
            get {
                return ResourceManager.GetString("R_Study03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسی.
        /// </summary>
        internal static string R_Study04 {
            get {
                return ResourceManager.GetString("R_Study04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاردانی.
        /// </summary>
        internal static string R_Study05 {
            get {
                return ResourceManager.GetString("R_Study05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیپلم.
        /// </summary>
        internal static string R_Study06 {
            get {
                return ResourceManager.GetString("R_Study06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت شود.
        /// </summary>
        internal static string R_Submit {
            get {
                return ResourceManager.GetString("R_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        internal static string R_tel {
            get {
                return ResourceManager.GetString("R_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string R_username {
            get {
                return ResourceManager.GetString("R_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه آشنايی با شرکت فاسکو.
        /// </summary>
        internal static string R_Visit_Phasco {
            get {
                return ResourceManager.GetString("R_Visit_Phasco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وب سایت.
        /// </summary>
        internal static string R_Websitge {
            get {
                return ResourceManager.GetString("R_Websitge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azarbayejan Eastern.
        /// </summary>
        internal static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khorasan Razavi.
        /// </summary>
        internal static string s10 {
            get {
                return ResourceManager.GetString("s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khorasan Northern.
        /// </summary>
        internal static string s11 {
            get {
                return ResourceManager.GetString("s11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khouzestan.
        /// </summary>
        internal static string s12 {
            get {
                return ResourceManager.GetString("s12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zanjan.
        /// </summary>
        internal static string s13 {
            get {
                return ResourceManager.GetString("s13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semnan.
        /// </summary>
        internal static string s14 {
            get {
                return ResourceManager.GetString("s14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistam &amp; Balochestan.
        /// </summary>
        internal static string s15 {
            get {
                return ResourceManager.GetString("s15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fars.
        /// </summary>
        internal static string s16 {
            get {
                return ResourceManager.GetString("s16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghazvin.
        /// </summary>
        internal static string s17 {
            get {
                return ResourceManager.GetString("s17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qom.
        /// </summary>
        internal static string s18 {
            get {
                return ResourceManager.GetString("s18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kordestan.
        /// </summary>
        internal static string s19 {
            get {
                return ResourceManager.GetString("s19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azarbayejan Western.
        /// </summary>
        internal static string s2 {
            get {
                return ResourceManager.GetString("s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerman.
        /// </summary>
        internal static string s20 {
            get {
                return ResourceManager.GetString("s20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kermanshah.
        /// </summary>
        internal static string s21 {
            get {
                return ResourceManager.GetString("s21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kohkiloye &amp; boyerahmad.
        /// </summary>
        internal static string s22 {
            get {
                return ResourceManager.GetString("s22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golestan.
        /// </summary>
        internal static string s23 {
            get {
                return ResourceManager.GetString("s23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gilan.
        /// </summary>
        internal static string s24 {
            get {
                return ResourceManager.GetString("s24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorestan.
        /// </summary>
        internal static string s25 {
            get {
                return ResourceManager.GetString("s25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazandaran.
        /// </summary>
        internal static string s26 {
            get {
                return ResourceManager.GetString("s26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markazi.
        /// </summary>
        internal static string s27 {
            get {
                return ResourceManager.GetString("s27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hormozgan.
        /// </summary>
        internal static string s28 {
            get {
                return ResourceManager.GetString("s28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamedan.
        /// </summary>
        internal static string s29 {
            get {
                return ResourceManager.GetString("s29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ardebil.
        /// </summary>
        internal static string s3 {
            get {
                return ResourceManager.GetString("s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazd.
        /// </summary>
        internal static string s30 {
            get {
                return ResourceManager.GetString("s30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isfehan.
        /// </summary>
        internal static string s4 {
            get {
                return ResourceManager.GetString("s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilam.
        /// </summary>
        internal static string s5 {
            get {
                return ResourceManager.GetString("s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boushehr.
        /// </summary>
        internal static string s6 {
            get {
                return ResourceManager.GetString("s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tehran.
        /// </summary>
        internal static string s7 {
            get {
                return ResourceManager.GetString("s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chahar Mahal &amp; Bakhtiari.
        /// </summary>
        internal static string s8 {
            get {
                return ResourceManager.GetString("s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khorasan Southern.
        /// </summary>
        internal static string s9 {
            get {
                return ResourceManager.GetString("s9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SatateEN.
        /// </summary>
        internal static string SatateF {
            get {
                return ResourceManager.GetString("SatateF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoping Cart is Empty.
        /// </summary>
        internal static string shoping_Cart_Empty {
            get {
                return ResourceManager.GetString("shoping_Cart_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home_Page_Text.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Success_Tra {
            get {
                return ResourceManager.GetString("Success_Tra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Manager.
        /// </summary>
        internal static string technical {
            get {
                return ResourceManager.GetString("technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeEN.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/Buy_Now_f.Gif.
        /// </summary>
        internal static string User_card_CheckOut {
            get {
                return ResourceManager.GetString("User_card_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This products not avliable to price.
        /// </summary>
        internal static string user_Card_NotAvliableProducts {
            get {
                return ResourceManager.GetString("user_Card_NotAvliableProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price :.
        /// </summary>
        internal static string User_card_total_Price {
            get {
                return ResourceManager.GetString("User_card_total_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Vote_Back {
            get {
                return ResourceManager.GetString("Vote_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Your idea has been reported successfully.
        /// </summary>
        internal static string Vote_Inserted {
            get {
                return ResourceManager.GetString("Vote_Inserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Vote_Result {
            get {
                return ResourceManager.GetString("Vote_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait ....
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSite.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p align=&quot;center&quot;&gt;&lt;font face=&quot;Tahoma&quot; size=&quot;2&quot;&gt;&lt;b&gt;با تشکر&lt;br&gt;
        ///&lt;br&gt;
        ///&lt;/b&gt;&amp;nbsp;ثبت نام شما با موفقیت انجام شد&lt;br&gt;
        ///خواهشمند است با &lt;a href=&quot;Login.aspx&quot;&gt;ورود به سیستم &lt;/a&gt;اطلاعات خود را کاملتر نمائید.&lt;/p&gt;&lt;/font&gt;.
        /// </summary>
        internal static string WelcomeMss {
            get {
                return ResourceManager.GetString("WelcomeMss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Time.
        /// </summary>
        internal static string Worktime {
            get {
                return ResourceManager.GetString("Worktime", resourceCulture);
            }
        }
    }
}
