//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phasco.Cpanel {
    
    public partial class PageMaker {
        protected System.Web.UI.WebControls.LinkButton LinkButton_New;
        protected System.Web.UI.WebControls.LinkButton LinkButton_Edit;
        protected System.Web.UI.WebControls.Label Lbl_Alarm;
        protected System.Web.UI.WebControls.MultiView MultiView1;
        protected System.Web.UI.WebControls.View View1;
        protected System.Web.UI.WebControls.TextBox TXT_Title_Page;
        protected System.Web.UI.WebControls.DropDownList DropDownList_Page;
        protected System.Web.UI.WebControls.DropDownList DropDownList_Lang;
        protected Telerik.WebControls.RadEditor RadEditor1;
        protected System.Web.UI.WebControls.Button Button_Insert;
        protected System.Web.UI.WebControls.View View2;
        protected System.Web.UI.WebControls.GridView GridView1;
    }
}
