//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phasco.Cpanel {
    
    public partial class Products {
        protected System.Web.UI.WebControls.MultiView MultiView1;
        protected System.Web.UI.WebControls.View View1;
        protected System.Web.UI.WebControls.LinkButton LinkButton_Back_Level;
        protected System.Web.UI.WebControls.LinkButton LinkButton_Insert_New_Company;
        protected System.Web.UI.WebControls.LinkButton LinkButton_Edit_Company;
        protected System.Web.UI.WebControls.TextBox Txt_Title;
        protected System.Web.UI.WebControls.Button Button_Insert;
        protected System.Web.UI.WebControls.GridView GRD_LIST;
        protected System.Web.UI.WebControls.View View2;
        protected System.Web.UI.WebControls.TextBox TextBox_q1;
        protected System.Web.UI.WebControls.TextBox TextBox_R1;
        protected System.Web.UI.WebControls.TextBox TextBox_q2;
        protected System.Web.UI.WebControls.TextBox TextBox_R2;
        protected System.Web.UI.WebControls.TextBox TextBox_q3;
        protected System.Web.UI.WebControls.TextBox TextBox_R3;
        protected System.Web.UI.WebControls.TextBox TextBox_q4;
        protected System.Web.UI.WebControls.TextBox TextBox_R4;
        protected System.Web.UI.WebControls.TextBox TextBox_q5;
        protected System.Web.UI.WebControls.TextBox TextBox_R5;
        protected System.Web.UI.WebControls.TextBox TextBox_q6;
        protected System.Web.UI.WebControls.TextBox TextBox_R6;
        protected System.Web.UI.WebControls.TextBox TextBox_q7;
        protected System.Web.UI.WebControls.TextBox TextBox_R7;
        protected System.Web.UI.WebControls.TextBox TextBox_q8;
        protected System.Web.UI.WebControls.TextBox TextBox_R8;
        protected System.Web.UI.WebControls.TextBox TextBox_q9;
        protected System.Web.UI.WebControls.TextBox TextBox_R9;
        protected System.Web.UI.WebControls.TextBox TextBox_q10;
        protected System.Web.UI.WebControls.TextBox TextBox_R10;
        protected System.Web.UI.WebControls.TextBox TextBox_q11;
        protected System.Web.UI.WebControls.TextBox TextBox_R11;
        protected System.Web.UI.WebControls.TextBox TextBox_q12;
        protected System.Web.UI.WebControls.TextBox TextBox_R12;
        protected System.Web.UI.WebControls.TextBox TextBox_Expire_Time;
        protected System.Web.UI.WebControls.TextBox TextBox_Price_Kit;
        protected System.Web.UI.WebControls.GridView GRD_Company;
        protected System.Web.UI.WebControls.Button Button_propertis_Insert;
        protected System.Web.UI.WebControls.Button Button_propertis_Edit;
        protected System.Web.UI.WebControls.View View3;
        protected System.Web.UI.WebControls.LinkButton LinkButton4;
        protected System.Web.UI.WebControls.LinkButton LinkButton_Back_ToList;
        protected System.Web.UI.WebControls.TextBox TextBox_COName;
        protected System.Web.UI.WebControls.TextBox TextBox_CODate;
        protected System.Web.UI.WebControls.TextBox TextBox_COCountry;
        protected System.Web.UI.WebControls.TextBox TextBox_COShort;
        protected System.Web.UI.WebControls.TextBox TextBox_COAbout;
        protected System.Web.UI.WebControls.Button Button_Company_Edit;
        protected System.Web.UI.WebControls.Button Button_Company_Insert;
        protected System.Web.UI.WebControls.View View4;
        protected System.Web.UI.WebControls.LinkButton LinkButton1;
        protected System.Web.UI.WebControls.LinkButton LinkButton5;
        protected System.Web.UI.WebControls.GridView Grd_Copmany;
        protected System.Web.UI.WebControls.View View5;
        protected System.Web.UI.WebControls.TextBox Text_Comment;
        protected System.Web.UI.WebControls.FileUpload FileUpload_DOc;
        protected System.Web.UI.WebControls.TextBox id;
        protected System.Web.UI.WebControls.Button Button_Doc;
        protected System.Web.UI.WebControls.LinkButton Link_Back;
        protected System.Web.UI.WebControls.GridView GridView_docs;
        protected System.Web.UI.WebControls.HiddenField HiddenField_Subjects_Id;
        protected System.Web.UI.WebControls.HiddenField HiddenField_Properties_Id;
        protected System.Web.UI.WebControls.HiddenField HiddenField_Company_Id;
        protected System.Web.UI.WebControls.HiddenField HiddenField_Company_attach_Id;
    }
}
