//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phasco.Cpanel {
    
    public partial class RequestUserPm {
        protected System.Web.UI.WebControls.MultiView MultiView1;
        protected System.Web.UI.WebControls.View View1;
        protected System.Web.UI.WebControls.GridView Grid_Sms;
        protected System.Web.UI.WebControls.View View2;
        protected System.Web.UI.WebControls.TextBox TextBox_PM;
        protected System.Web.UI.WebControls.FileUpload FileUpload_Attach;
        protected System.Web.UI.WebControls.Button Button_Send;
        protected System.Web.UI.WebControls.HiddenField HiddenField_Id;
    }
}
