//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phasco_webproject.UI {
    
    public partial class SendMss {
        protected System.Web.UI.WebControls.MultiView MultiView1;
        protected System.Web.UI.WebControls.View View1;
        protected System.Web.UI.WebControls.TextBox TextBox_Title;
        protected System.Web.UI.WebControls.Label Label_Sender_Name;
        protected System.Web.UI.UpdatePanel UpdatePanel1;
        protected System.Web.UI.WebControls.TextBox TextBox_ReciverUId;
        protected System.Web.UI.WebControls.LinkButton LinkButton_CheckId;
        protected System.Web.UI.WebControls.Label Label_Alarm;
        protected System.Web.UI.WebControls.TextBox TextBox_Recivername;
        protected System.Web.UI.UpdateProgress UpdateProgress1;
        protected Telerik.WebControls.RadEditor RadEditor1;
        protected System.Web.UI.WebControls.FileUpload FileUpload_Attach;
        protected System.Web.UI.WebControls.CheckBox CheckBox_Outbox;
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.View View2;
        protected System.Web.UI.WebControls.HiddenField HiddenField_Id;
    }
}
