//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phasco_webproject.UI {
    
    public partial class Vote {
        protected System.Web.UI.WebControls.MultiView MultiView1;
        protected System.Web.UI.WebControls.View View1;
        protected System.Web.UI.WebControls.Label Lbl_Alarm;
        protected System.Web.UI.WebControls.Label Lbl_Question;
        protected System.Web.UI.WebControls.RadioButtonList RadioButtonList_Item;
        protected System.Web.UI.WebControls.LinkButton LinkButton_View_Result;
        protected System.Web.UI.WebControls.Button Button_INs;
        protected System.Web.UI.WebControls.View View2;
        protected System.Web.UI.WebControls.HiddenField total_vote;
        protected System.Web.UI.WebControls.HiddenField total_item;
        protected System.Web.UI.WebControls.Repeater Repeater_Vote;
        protected System.Web.UI.WebControls.LinkButton LinkButton_Back_Vote;
    }
}
